on: [workflow_dispatch]

name: Prepare the ipynb for the Guidelines page
jobs:
  prepare_guidelines:
    runs-on: ubuntu-latest
    name: Ipynb for publishing
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: General introduction
        id: introduction
        uses: c2dh/journal-of-digital-history-ipynb-skim-action@master
        with:
          notebook: 'examples/Author_Guideline/AuthorGuideline-introduction-raw.ipynb'
          output_notebook: 'examples/Author_Guideline/AuthorGuideline-introduction.ipynb'
      - name: mac os installation
        id: mac
        uses: c2dh/journal-of-digital-history-ipynb-skim-action@master
        with:
          notebook: 'examples/Author_Guideline/AuthorGuideline-mac-raw.ipynb'
          output_notebook: 'examples/Author_Guideline/AuthorGuideline-mac.ipynb'
      - name: windows installation
        id: windows
        uses: c2dh/journal-of-digital-history-ipynb-skim-action@master
        with:
          notebook: 'examples/Author_Guideline/AuthorGuideline-windows-raw.ipynb'
          output_notebook: 'examples/Author_Guideline/AuthorGuideline-windows.ipynb'
      - name: styling and makeup
        id: styling
        uses: c2dh/journal-of-digital-history-ipynb-skim-action@master
        with:
          notebook: 'examples/Author_Guideline/AuthorGuideline-styling-raw.ipynb'
          output_notebook: 'examples/Author_Guideline/AuthorGuideline-styling.ipynb'
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
